[package]
name = "typefun"
version = "0.2.0"
edition = "2021"
authors = ["Asger Hautop Drewsen <asger@tyilo.com>"]
description = "Emulating various values at compile-time using types"
license = "MIT OR Apache-2.0"

[dependencies]
